import Link from "next/link";
import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";

export const metadata: Metadata = {
  title: "FAQ",
  description: "Common questions about reconstitution, storage, verification, and tools.",
};

const FAQ_ITEMS: { q: string; a: React.ReactNode }[] = [
  {
    q: "What water should I use for reconstitution?",
    a: "Bacteriostatic water (BAC water) or sterile diluent per your protocol. Do not use plain tap or distilled water. Check your lab or product instructions.",
  },
  {
    q: "How long can reconstituted peptide be stored?",
    a: "Many peptides are stable 2–8 °C for about 30 days after reconstitution. This is a rough guide; follow your product leaflet or protocol. Use the stability helper on the Guide page to get a suggested use-by date.",
  },
  {
    q: "Where can I verify purity and get reports?",
    a: "Third-party labs such as Janoshik offer HPLC purity, mass spec identity, and potency testing. See our Purity & Verify page for Janoshik and the public results database (public.janoshik.com). Use the report verification helper to open the official verification page with your task ID.",
  },
  {
    q: "How do I know my Janoshik report is real?",
    a: "Every report has a task ID. Go to Janoshik's website and use \"Verify report\" (or the link generated by our verification helper), enter the task ID, and confirm the content matches your report. Do not trust reports that cannot be verified on the lab's official site.",
  },
  {
    q: "What if my syringe is 0.3 mL or 0.5 mL, not 1 mL?",
    a: "The Reconstitution & Dosing Calculator lets you choose syringe size (0.3 mL / 30 units, 0.5 mL / 50 units, or 1 mL / 100 units). It will show the volume to draw and the corresponding units for your syringe.",
  },
  {
    q: "How many vials do I need for a cycle?",
    a: "Use the Vial & Cycle Calculator under Tools: enter vial size (mg), dose per injection (mcg), and injections per day to see how many days one vial lasts, then enter target days to get the number of vials needed.",
  },
];

export default function FAQPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <Breadcrumbs items={[{ label: "Help", href: "/guide" }, { label: "FAQ" }]} />
      <h1 className="mt-2 text-3xl font-bold text-slate-900">FAQ</h1>
      <p className="mt-2 text-slate-600">
        Common questions about reconstitution, storage, verification, and tools.
      </p>

      <dl className="mt-8 space-y-6">
        {FAQ_ITEMS.map((item, i) => (
          <div key={i} className="card">
            <dt className="font-semibold text-slate-900">{item.q}</dt>
            <dd className="mt-2 text-slate-600">{item.a}</dd>
          </div>
        ))}
      </dl>

      <p className="mt-8 text-sm text-slate-500">
        <Link href="/guide" className="link-inline">Reconstitution & Dosing Guide</Link>
        {" · "}
        <Link href="/verify" className="link-inline">Purity & Verify</Link>
        {" · "}
        <Link href="/tools" className="link-inline">Tools</Link>
      </p>
    </div>
  );
}
